-- profiles

INSERT INTO user_profile (description, value) VALUES ('Admin', 1);
INSERT INTO user_profile (description, value) VALUES ('Customer', 2);

-- Product categories
INSERT INTO product_category (description, code) VALUES ('Eletrônicos', 1);
INSERT INTO product_category (description, code) VALUES ('Bebidas', 2);
INSERT INTO product_category (description, code) VALUES ('Brinquedos', 3);
INSERT INTO product_category (description, code) VALUES ('Roupas', 4);

-- State data

INSERT INTO state (uf_code, name, UF, region) VALUES (35, 'São Paulo', 'SP', 3);
INSERT INTO state (uf_code, name, UF, region) VALUES (33, 'Rio de Janeiro', 'RJ', 3);

-- Cities from Sao Paulo state

INSERT INTO city (id_state, name) values (1,'Adamantina');
INSERT INTO city (id_state, name) values (1,'Adolfo');
INSERT INTO city (id_state, name) values (1,'Aguaí');
INSERT INTO city (id_state, name) values (1,'Águas da Prata');
INSERT INTO city (id_state, name) values (1,'Águas de Lindóia');
INSERT INTO city (id_state, name) values (1,'Águas de Santa Bárbara');
INSERT INTO city (id_state, name) values (1,'Águas de São Pedro');
INSERT INTO city (id_state, name) values (1,'Agudos');
INSERT INTO city (id_state, name) values (1,'Alambari');
INSERT INTO city (id_state, name) values (1,'Alfredo Marcondes');
INSERT INTO city (id_state, name) values (1,'Altair');
INSERT INTO city (id_state, name) values (1,'Altinópolis');
INSERT INTO city (id_state, name) values (1,'Alto Alegre');
INSERT INTO city (id_state, name) values (1,'Alumínio');
INSERT INTO city (id_state, name) values (1,'Álvares Florence');
INSERT INTO city (id_state, name) values (1,'Álvares Machado');
INSERT INTO city (id_state, name) values (1,'Álvaro de Carvalho');
INSERT INTO city (id_state, name) values (1,'Alvinlândia');
INSERT INTO city (id_state, name) values (1,'Americana');
INSERT INTO city (id_state, name) values (1,'Américo Brasiliense');
INSERT INTO city (id_state, name) values (1,'Américo de Campos');
INSERT INTO city (id_state, name) values (1,'Amparo');
INSERT INTO city (id_state, name) values (1,'Analândia');
INSERT INTO city (id_state, name) values (1,'Andradina');
INSERT INTO city (id_state, name) values (1,'Angatuba');
INSERT INTO city (id_state, name) values (1,'Anhembi');
INSERT INTO city (id_state, name) values (1,'Anhumas');
INSERT INTO city (id_state, name) values (1,'Aparecida');
INSERT INTO city (id_state, name) values (1,'Aparecida D''Oeste');
INSERT INTO city (id_state, name) values (1,'Apiaí');
INSERT INTO city (id_state, name) values (1,'Araçariguama');
INSERT INTO city (id_state, name) values (1,'Araçatuba');
INSERT INTO city (id_state, name) values (1,'Araçoiaba da Serra');
INSERT INTO city (id_state, name) values (1,'Aramina');
INSERT INTO city (id_state, name) values (1,'Arandu');
INSERT INTO city (id_state, name) values (1,'Arapeí');
INSERT INTO city (id_state, name) values (1,'Araraquara');
INSERT INTO city (id_state, name) values (1,'Araras');
INSERT INTO city (id_state, name) values (1,'Arco-Íris');
INSERT INTO city (id_state, name) values (1,'Arealva');
INSERT INTO city (id_state, name) values (1,'Areias');
INSERT INTO city (id_state, name) values (1,'Areiópolis');
INSERT INTO city (id_state, name) values (1,'Ariranha');
INSERT INTO city (id_state, name) values (1,'Artur Nogueira');
INSERT INTO city (id_state, name) values (1,'Arujá');
INSERT INTO city (id_state, name) values (1,'Aspásia');
INSERT INTO city (id_state, name) values (1,'Assis');
INSERT INTO city (id_state, name) values (1,'Atibaia');
INSERT INTO city (id_state, name) values (1,'Auriflama');
INSERT INTO city (id_state, name) values (1,'Avaí');
INSERT INTO city (id_state, name) values (1,'Avanhandava');
INSERT INTO city (id_state, name) values (1,'Avaré');
INSERT INTO city (id_state, name) values (1,'Bady Bassitt');
INSERT INTO city (id_state, name) values (1,'Balbinos');
INSERT INTO city (id_state, name) values (1,'Bálsamo');
INSERT INTO city (id_state, name) values (1,'Bananal');
INSERT INTO city (id_state, name) values (1,'Barão de Antonina');
INSERT INTO city (id_state, name) values (1,'Barbosa');
INSERT INTO city (id_state, name) values (1,'Bariri');
INSERT INTO city (id_state, name) values (1,'Barra Bonita');
INSERT INTO city (id_state, name) values (1,'Barra do Chapéu');
INSERT INTO city (id_state, name) values (1,'Barra do Turvo');
INSERT INTO city (id_state, name) values (1,'Barretos');
INSERT INTO city (id_state, name) values (1,'Barrinha');
INSERT INTO city (id_state, name) values (1,'Barueri');
INSERT INTO city (id_state, name) values (1,'Bastos');
INSERT INTO city (id_state, name) values (1,'Batatais');
INSERT INTO city (id_state, name) values (1,'Bauru');
INSERT INTO city (id_state, name) values (1,'Bebedouro');
INSERT INTO city (id_state, name) values (1,'Bento de Abreu');
INSERT INTO city (id_state, name) values (1,'Bernardino de Campos');
INSERT INTO city (id_state, name) values (1,'Bertioga');
INSERT INTO city (id_state, name) values (1,'Bilac');
INSERT INTO city (id_state, name) values (1,'Birigui');
INSERT INTO city (id_state, name) values (1,'Biritiba-Mirim');
INSERT INTO city (id_state, name) values (1,'Boa Esperança do Sul');
INSERT INTO city (id_state, name) values (1,'Bocaina');
INSERT INTO city (id_state, name) values (1,'Bofete');
INSERT INTO city (id_state, name) values (1,'Boituva');
INSERT INTO city (id_state, name) values (1,'Bom Jesus dos Perdões');
INSERT INTO city (id_state, name) values (1,'Bom Sucesso de Itararé');
INSERT INTO city (id_state, name) values (1,'Borá');
INSERT INTO city (id_state, name) values (1,'Boracéia');
INSERT INTO city (id_state, name) values (1,'Borborema');
INSERT INTO city (id_state, name) values (1,'Borebi');
INSERT INTO city (id_state, name) values (1,'Botucatu');
INSERT INTO city (id_state, name) values (1,'Bragança Paulista');
INSERT INTO city (id_state, name) values (1,'Braúna');
INSERT INTO city (id_state, name) values (1,'Brejo Alegre');
INSERT INTO city (id_state, name) values (1,'Brodowski');
INSERT INTO city (id_state, name) values (1,'Brotas');
INSERT INTO city (id_state, name) values (1,'Buri');
INSERT INTO city (id_state, name) values (1,'Buritama');
INSERT INTO city (id_state, name) values (1,'Buritizal');
INSERT INTO city (id_state, name) values (1,'Cabrália Paulista');
INSERT INTO city (id_state, name) values (1,'Cabreúva');
INSERT INTO city (id_state, name) values (1,'Caçapava');
INSERT INTO city (id_state, name) values (1,'Cachoeira Paulista');
INSERT INTO city (id_state, name) values (1,'Caconde');
INSERT INTO city (id_state, name) values (1,'Cafelândia');
INSERT INTO city (id_state, name) values (1,'Caiabu');
INSERT INTO city (id_state, name) values (1,'Caieiras');
INSERT INTO city (id_state, name) values (1,'Caiuá');
INSERT INTO city (id_state, name) values (1,'Cajamar');
INSERT INTO city (id_state, name) values (1,'Cajati');
INSERT INTO city (id_state, name) values (1,'Cajobi');
INSERT INTO city (id_state, name) values (1,'Cajuru');
INSERT INTO city (id_state, name) values (1,'Campina do Monte Alegre');
INSERT INTO city (id_state, name) values (1,'Campinas');
INSERT INTO city (id_state, name) values (1,'Campo Limpo Paulista');
INSERT INTO city (id_state, name) values (1,'Campos do Jordão');
INSERT INTO city (id_state, name) values (1,'Campos Novos Paulista');
INSERT INTO city (id_state, name) values (1,'Cananéia');
INSERT INTO city (id_state, name) values (1,'Canas');
INSERT INTO city (id_state, name) values (1,'Cândido Mota');
INSERT INTO city (id_state, name) values (1,'Cândido Rodrigues');
INSERT INTO city (id_state, name) values (1,'Canitar');
INSERT INTO city (id_state, name) values (1,'Capão Bonito');
INSERT INTO city (id_state, name) values (1,'Capela do Alto');
INSERT INTO city (id_state, name) values (1,'Capivari');
INSERT INTO city (id_state, name) values (1,'Caraguatatuba');
INSERT INTO city (id_state, name) values (1,'Carapicuíba');
INSERT INTO city (id_state, name) values (1,'Cardoso');
INSERT INTO city (id_state, name) values (1,'Casa Branca');
INSERT INTO city (id_state, name) values (1,'Cássia dos Coqueiros');
INSERT INTO city (id_state, name) values (1,'Castilho');
INSERT INTO city (id_state, name) values (1,'Catanduva');
INSERT INTO city (id_state, name) values (1,'Catiguá');
INSERT INTO city (id_state, name) values (1,'Cedral');
INSERT INTO city (id_state, name) values (1,'Cerqueira César');
INSERT INTO city (id_state, name) values (1,'Cerquilho');
INSERT INTO city (id_state, name) values (1,'Cesário Lange');
INSERT INTO city (id_state, name) values (1,'Charqueada');
INSERT INTO city (id_state, name) values (1,'Clementina');
INSERT INTO city (id_state, name) values (1,'Colina');
INSERT INTO city (id_state, name) values (1,'Colômbia');
INSERT INTO city (id_state, name) values (1,'Conchal');
INSERT INTO city (id_state, name) values (1,'Conchas');
INSERT INTO city (id_state, name) values (1,'Cordeirópolis');
INSERT INTO city (id_state, name) values (1,'Coroados');
INSERT INTO city (id_state, name) values (1,'Coronel Macedo');
INSERT INTO city (id_state, name) values (1,'Corumbataí');
INSERT INTO city (id_state, name) values (1,'Cosmópolis');
INSERT INTO city (id_state, name) values (1,'Cosmorama');
INSERT INTO city (id_state, name) values (1,'Cotia');
INSERT INTO city (id_state, name) values (1,'Cravinhos');
INSERT INTO city (id_state, name) values (1,'Cristais Paulista');
INSERT INTO city (id_state, name) values (1,'Cruzália');
INSERT INTO city (id_state, name) values (1,'Cruzeiro');
INSERT INTO city (id_state, name) values (1,'Cubatão');
INSERT INTO city (id_state, name) values (1,'Cunha');
INSERT INTO city (id_state, name) values (1,'Descalvado');
INSERT INTO city (id_state, name) values (1,'Diadema');
INSERT INTO city (id_state, name) values (1,'Dirce Reis');
INSERT INTO city (id_state, name) values (1,'Divinolândia');
INSERT INTO city (id_state, name) values (1,'Dobrada');
INSERT INTO city (id_state, name) values (1,'Dois Córregos');
INSERT INTO city (id_state, name) values (1,'Dolcinópolis');
INSERT INTO city (id_state, name) values (1,'Dourado');
INSERT INTO city (id_state, name) values (1,'Dracena');
INSERT INTO city (id_state, name) values (1,'Duartina');
INSERT INTO city (id_state, name) values (1,'Dumont');
INSERT INTO city (id_state, name) values (1,'Echaporã');
INSERT INTO city (id_state, name) values (1,'Eldorado');
INSERT INTO city (id_state, name) values (1,'Elias Fausto');
INSERT INTO city (id_state, name) values (1,'Elisiário');
INSERT INTO city (id_state, name) values (1,'Embaúba');
INSERT INTO city (id_state, name) values (1,'Embu das Artes');
INSERT INTO city (id_state, name) values (1,'Embu-Guaçu');
INSERT INTO city (id_state, name) values (1,'Emilianópolis');
INSERT INTO city (id_state, name) values (1,'Engenheiro Coelho');
INSERT INTO city (id_state, name) values (1,'Espírito Santo do Pinhal');
INSERT INTO city (id_state, name) values (1,'Espírito Santo do Turvo');
INSERT INTO city (id_state, name) values (1,'Estrela D''Oeste');
INSERT INTO city (id_state, name) values (1,'Estrela do Norte');
INSERT INTO city (id_state, name) values (1,'Euclides da Cunha Paulista');
INSERT INTO city (id_state, name) values (1,'Fartura');
INSERT INTO city (id_state, name) values (1,'Fernandópolis');
INSERT INTO city (id_state, name) values (1,'Fernando Prestes');
INSERT INTO city (id_state, name) values (1,'Fernão');
INSERT INTO city (id_state, name) values (1,'Ferraz de Vasconcelos');
INSERT INTO city (id_state, name) values (1,'Flora Rica');
INSERT INTO city (id_state, name) values (1,'Floreal');
INSERT INTO city (id_state, name) values (1,'Flórida Paulista');
INSERT INTO city (id_state, name) values (1,'Florínia');
INSERT INTO city (id_state, name) values (1,'Franca');
INSERT INTO city (id_state, name) values (1,'Francisco Morato');
INSERT INTO city (id_state, name) values (1,'Franco da Rocha');
INSERT INTO city (id_state, name) values (1,'Gabriel Monteiro');
INSERT INTO city (id_state, name) values (1,'Gália');
INSERT INTO city (id_state, name) values (1,'Garça');
INSERT INTO city (id_state, name) values (1,'Gastão Vidigal');
INSERT INTO city (id_state, name) values (1,'Gavião Peixoto');
INSERT INTO city (id_state, name) values (1,'General Salgado');
INSERT INTO city (id_state, name) values (1,'Getulina');
INSERT INTO city (id_state, name) values (1,'Glicério');
INSERT INTO city (id_state, name) values (1,'Guaiçara');
INSERT INTO city (id_state, name) values (1,'Guaimbê');
INSERT INTO city (id_state, name) values (1,'Guaíra');
INSERT INTO city (id_state, name) values (1,'Guapiaçu');
INSERT INTO city (id_state, name) values (1,'Guapiara');
INSERT INTO city (id_state, name) values (1,'Guará');
INSERT INTO city (id_state, name) values (1,'Guaraçaí');
INSERT INTO city (id_state, name) values (1,'Guaraci');
INSERT INTO city (id_state, name) values (1,'Guarani D''Oeste');
INSERT INTO city (id_state, name) values (1,'Guarantã');
INSERT INTO city (id_state, name) values (1,'Guararapes');
INSERT INTO city (id_state, name) values (1,'Guararema');
INSERT INTO city (id_state, name) values (1,'Guaratinguetá');
INSERT INTO city (id_state, name) values (1,'Guareí');
INSERT INTO city (id_state, name) values (1,'Guariba');
INSERT INTO city (id_state, name) values (1,'Guarujá');
INSERT INTO city (id_state, name) values (1,'Guarulhos');
INSERT INTO city (id_state, name) values (1,'Guatapará');
INSERT INTO city (id_state, name) values (1,'Guzolândia');
INSERT INTO city (id_state, name) values (1,'Herculândia');
INSERT INTO city (id_state, name) values (1,'Holambra');
INSERT INTO city (id_state, name) values (1,'Hortolândia');
INSERT INTO city (id_state, name) values (1,'Iacanga');
INSERT INTO city (id_state, name) values (1,'Iacri');
INSERT INTO city (id_state, name) values (1,'Iaras');
INSERT INTO city (id_state, name) values (1,'Ibaté');
INSERT INTO city (id_state, name) values (1,'Ibirá');
INSERT INTO city (id_state, name) values (1,'Ibirarema');
INSERT INTO city (id_state, name) values (1,'Ibitinga');
INSERT INTO city (id_state, name) values (1,'Ibiúna');
INSERT INTO city (id_state, name) values (1,'Icém');
INSERT INTO city (id_state, name) values (1,'Iepê');
INSERT INTO city (id_state, name) values (1,'Igaraçu do Tietê');
INSERT INTO city (id_state, name) values (1,'Igarapava');
INSERT INTO city (id_state, name) values (1,'Igaratá');
INSERT INTO city (id_state, name) values (1,'Iguape');
INSERT INTO city (id_state, name) values (1,'Ilhabela');
INSERT INTO city (id_state, name) values (1,'Ilha Comprida');
INSERT INTO city (id_state, name) values (1,'Ilha Solteira');
INSERT INTO city (id_state, name) values (1,'Indaiatuba');
INSERT INTO city (id_state, name) values (1,'Indiana');
INSERT INTO city (id_state, name) values (1,'Indiaporã');
INSERT INTO city (id_state, name) values (1,'Inúbia Paulista');
INSERT INTO city (id_state, name) values (1,'Ipaussu');
INSERT INTO city (id_state, name) values (1,'Iperó');
INSERT INTO city (id_state, name) values (1,'Ipeúna');
INSERT INTO city (id_state, name) values (1,'Ipiguá');
INSERT INTO city (id_state, name) values (1,'Iporanga');
INSERT INTO city (id_state, name) values (1,'Ipuã');
INSERT INTO city (id_state, name) values (1,'Iracemápolis');
INSERT INTO city (id_state, name) values (1,'Irapuã');
INSERT INTO city (id_state, name) values (1,'Irapuru');
INSERT INTO city (id_state, name) values (1,'Itaberá');
INSERT INTO city (id_state, name) values (1,'Itaí');
INSERT INTO city (id_state, name) values (1,'Itajobi');
INSERT INTO city (id_state, name) values (1,'Itaju');
INSERT INTO city (id_state, name) values (1,'Itanhaém');
INSERT INTO city (id_state, name) values (1,'Itaóca');
INSERT INTO city (id_state, name) values (1,'Itapecerica da Serra');
INSERT INTO city (id_state, name) values (1,'Itapetininga');
INSERT INTO city (id_state, name) values (1,'Itapeva');
INSERT INTO city (id_state, name) values (1,'Itapevi');
INSERT INTO city (id_state, name) values (1,'Itapira');
INSERT INTO city (id_state, name) values (1,'Itapirapuã Paulista');
INSERT INTO city (id_state, name) values (1,'Itápolis');
INSERT INTO city (id_state, name) values (1,'Itaporanga');
INSERT INTO city (id_state, name) values (1,'Itapuí');
INSERT INTO city (id_state, name) values (1,'Itapura');
INSERT INTO city (id_state, name) values (1,'Itaquaquecetuba');
INSERT INTO city (id_state, name) values (1,'Itararé');
INSERT INTO city (id_state, name) values (1,'Itariri');
INSERT INTO city (id_state, name) values (1,'Itatiba');
INSERT INTO city (id_state, name) values (1,'Itatinga');
INSERT INTO city (id_state, name) values (1,'Itirapina');
INSERT INTO city (id_state, name) values (1,'Itirapuã');
INSERT INTO city (id_state, name) values (1,'Itobi');
INSERT INTO city (id_state, name) values (1,'Itu');
INSERT INTO city (id_state, name) values (1,'Itupeva');
INSERT INTO city (id_state, name) values (1,'Ituverava');
INSERT INTO city (id_state, name) values (1,'Jaborandi');
INSERT INTO city (id_state, name) values (1,'Jaboticabal');
INSERT INTO city (id_state, name) values (1,'Jacareí');
INSERT INTO city (id_state, name) values (1,'Jaci');
INSERT INTO city (id_state, name) values (1,'Jacupiranga');
INSERT INTO city (id_state, name) values (1,'Jaguariúna');
INSERT INTO city (id_state, name) values (1,'Jales');
INSERT INTO city (id_state, name) values (1,'Jambeiro');
INSERT INTO city (id_state, name) values (1,'Jandira');
INSERT INTO city (id_state, name) values (1,'Jardinópolis');
INSERT INTO city (id_state, name) values (1,'Jarinu');
INSERT INTO city (id_state, name) values (1,'Jaú');
INSERT INTO city (id_state, name) values (1,'Jeriquara');
INSERT INTO city (id_state, name) values (1,'Joanópolis');
INSERT INTO city (id_state, name) values (1,'João Ramalho');
INSERT INTO city (id_state, name) values (1,'José Bonifácio');
INSERT INTO city (id_state, name) values (1,'Júlio Mesquita');
INSERT INTO city (id_state, name) values (1,'Jumirim');
INSERT INTO city (id_state, name) values (1,'Jundiaí');
INSERT INTO city (id_state, name) values (1,'Junqueirópolis');
INSERT INTO city (id_state, name) values (1,'Juquiá');
INSERT INTO city (id_state, name) values (1,'Juquitiba');
INSERT INTO city (id_state, name) values (1,'Lagoinha');
INSERT INTO city (id_state, name) values (1,'Laranjal Paulista');
INSERT INTO city (id_state, name) values (1,'Lavínia');
INSERT INTO city (id_state, name) values (1,'Lavrinhas');
INSERT INTO city (id_state, name) values (1,'Leme');
INSERT INTO city (id_state, name) values (1,'Lençóis Paulista');
INSERT INTO city (id_state, name) values (1,'Limeira');
INSERT INTO city (id_state, name) values (1,'Lindóia');
INSERT INTO city (id_state, name) values (1,'Lins');
INSERT INTO city (id_state, name) values (1,'Lorena');
INSERT INTO city (id_state, name) values (1,'Lourdes');
INSERT INTO city (id_state, name) values (1,'Louveira');
INSERT INTO city (id_state, name) values (1,'Lucélia');
INSERT INTO city (id_state, name) values (1,'Lucianópolis');
INSERT INTO city (id_state, name) values (1,'Luís Antônio');
INSERT INTO city (id_state, name) values (1,'Luiziânia');
INSERT INTO city (id_state, name) values (1,'Lupércio');
INSERT INTO city (id_state, name) values (1,'Lutécia');
INSERT INTO city (id_state, name) values (1,'Macatuba');
INSERT INTO city (id_state, name) values (1,'Macaubal');
INSERT INTO city (id_state, name) values (1,'Macedônia');
INSERT INTO city (id_state, name) values (1,'Magda');
INSERT INTO city (id_state, name) values (1,'Mairinque');
INSERT INTO city (id_state, name) values (1,'Mairiporã');
INSERT INTO city (id_state, name) values (1,'Manduri');
INSERT INTO city (id_state, name) values (1,'Marabá Paulista');
INSERT INTO city (id_state, name) values (1,'Maracaí');
INSERT INTO city (id_state, name) values (1,'Marapoama');
INSERT INTO city (id_state, name) values (1,'Mariápolis');
INSERT INTO city (id_state, name) values (1,'Marília');
INSERT INTO city (id_state, name) values (1,'Marinópolis');
INSERT INTO city (id_state, name) values (1,'Martinópolis');
INSERT INTO city (id_state, name) values (1,'Matão');
INSERT INTO city (id_state, name) values (1,'Mauá');
INSERT INTO city (id_state, name) values (1,'Mendonça');
INSERT INTO city (id_state, name) values (1,'Meridiano');
INSERT INTO city (id_state, name) values (1,'Mesópolis');
INSERT INTO city (id_state, name) values (1,'Miguelópolis');
INSERT INTO city (id_state, name) values (1,'Mineiros do Tietê');
INSERT INTO city (id_state, name) values (1,'Miracatu');
INSERT INTO city (id_state, name) values (1,'Mira Estrela');
INSERT INTO city (id_state, name) values (1,'Mirandópolis');
INSERT INTO city (id_state, name) values (1,'Mirante do Paranapanema');
INSERT INTO city (id_state, name) values (1,'Mirassol');
INSERT INTO city (id_state, name) values (1,'Mirassolândia');
INSERT INTO city (id_state, name) values (1,'Mococa');
INSERT INTO city (id_state, name) values (1,'Mogi das Cruzes');
INSERT INTO city (id_state, name) values (1,'Mogi Guaçu');
INSERT INTO city (id_state, name) values (1,'Moji Mirim');
INSERT INTO city (id_state, name) values (1,'Mombuca');
INSERT INTO city (id_state, name) values (1,'Monções');
INSERT INTO city (id_state, name) values (1,'Mongaguá');
INSERT INTO city (id_state, name) values (1,'Monte Alegre do Sul');
INSERT INTO city (id_state, name) values (1,'Monte Alto');
INSERT INTO city (id_state, name) values (1,'Monte Aprazível');
INSERT INTO city (id_state, name) values (1,'Monte Azul Paulista');
INSERT INTO city (id_state, name) values (1,'Monte Castelo');
INSERT INTO city (id_state, name) values (1,'Monteiro Lobato');
INSERT INTO city (id_state, name) values (1,'Monte Mor');
INSERT INTO city (id_state, name) values (1,'Morro Agudo');
INSERT INTO city (id_state, name) values (1,'Morungaba');
INSERT INTO city (id_state, name) values (1,'Motuca');
INSERT INTO city (id_state, name) values (1,'Murutinga do Sul');
INSERT INTO city (id_state, name) values (1,'Nantes');
INSERT INTO city (id_state, name) values (1,'Narandiba');
INSERT INTO city (id_state, name) values (1,'Natividade da Serra');
INSERT INTO city (id_state, name) values (1,'Nazaré Paulista');
INSERT INTO city (id_state, name) values (1,'Neves Paulista');
INSERT INTO city (id_state, name) values (1,'Nhandeara');
INSERT INTO city (id_state, name) values (1,'Nipoã');
INSERT INTO city (id_state, name) values (1,'Nova Aliança');
INSERT INTO city (id_state, name) values (1,'Nova Campina');
INSERT INTO city (id_state, name) values (1,'Nova Canaã Paulista');
INSERT INTO city (id_state, name) values (1,'Nova Castilho');
INSERT INTO city (id_state, name) values (1,'Nova Europa');
INSERT INTO city (id_state, name) values (1,'Nova Granada');
INSERT INTO city (id_state, name) values (1,'Nova Guataporanga');
INSERT INTO city (id_state, name) values (1,'Nova Independência');
INSERT INTO city (id_state, name) values (1,'Novais');
INSERT INTO city (id_state, name) values (1,'Nova Luzitânia');
INSERT INTO city (id_state, name) values (1,'Nova Odessa');
INSERT INTO city (id_state, name) values (1,'Novo Horizonte');
INSERT INTO city (id_state, name) values (1,'Nuporanga');
INSERT INTO city (id_state, name) values (1,'Ocauçu');
INSERT INTO city (id_state, name) values (1,'Óleo');
INSERT INTO city (id_state, name) values (1,'Olímpia');
INSERT INTO city (id_state, name) values (1,'Onda Verde');
INSERT INTO city (id_state, name) values (1,'Oriente');
INSERT INTO city (id_state, name) values (1,'Orindiúva');
INSERT INTO city (id_state, name) values (1,'Orlândia');
INSERT INTO city (id_state, name) values (1,'Osasco');
INSERT INTO city (id_state, name) values (1,'Oscar Bressane');
INSERT INTO city (id_state, name) values (1,'Osvaldo Cruz');
INSERT INTO city (id_state, name) values (1,'Ourinhos');
INSERT INTO city (id_state, name) values (1,'Ouroeste');
INSERT INTO city (id_state, name) values (1,'Ouro Verde');
INSERT INTO city (id_state, name) values (1,'Pacaembu');
INSERT INTO city (id_state, name) values (1,'Palestina');
INSERT INTO city (id_state, name) values (1,'Palmares Paulista');
INSERT INTO city (id_state, name) values (1,'Palmeira D''Oeste');
INSERT INTO city (id_state, name) values (1,'Palmital');
INSERT INTO city (id_state, name) values (1,'Panorama');
INSERT INTO city (id_state, name) values (1,'Paraguaçu Paulista');
INSERT INTO city (id_state, name) values (1,'Paraibuna');
INSERT INTO city (id_state, name) values (1,'Paraíso');
INSERT INTO city (id_state, name) values (1,'Paranapanema');
INSERT INTO city (id_state, name) values (1,'Paranapuã');
INSERT INTO city (id_state, name) values (1,'Parapuã');
INSERT INTO city (id_state, name) values (1,'Pardinho');
INSERT INTO city (id_state, name) values (1,'Pariquera-Açu');
INSERT INTO city (id_state, name) values (1,'Parisi');
INSERT INTO city (id_state, name) values (1,'Patrocínio Paulista');
INSERT INTO city (id_state, name) values (1,'Paulicéia');
INSERT INTO city (id_state, name) values (1,'Paulínia');
INSERT INTO city (id_state, name) values (1,'Paulistânia');
INSERT INTO city (id_state, name) values (1,'Paulo de Faria');
INSERT INTO city (id_state, name) values (1,'Pederneiras');
INSERT INTO city (id_state, name) values (1,'Pedra Bela');
INSERT INTO city (id_state, name) values (1,'Pedranópolis');
INSERT INTO city (id_state, name) values (1,'Pedregulho');
INSERT INTO city (id_state, name) values (1,'Pedreira');
INSERT INTO city (id_state, name) values (1,'Pedrinhas Paulista');
INSERT INTO city (id_state, name) values (1,'Pedro de Toledo');
INSERT INTO city (id_state, name) values (1,'Penápolis');
INSERT INTO city (id_state, name) values (1,'Pereira Barreto');
INSERT INTO city (id_state, name) values (1,'Pereiras');
INSERT INTO city (id_state, name) values (1,'Peruíbe');
INSERT INTO city (id_state, name) values (1,'Piacatu');
INSERT INTO city (id_state, name) values (1,'Piedade');
INSERT INTO city (id_state, name) values (1,'Pilar do Sul');
INSERT INTO city (id_state, name) values (1,'Pindamonhangaba');
INSERT INTO city (id_state, name) values (1,'Pindorama');
INSERT INTO city (id_state, name) values (1,'Pinhalzinho');
INSERT INTO city (id_state, name) values (1,'Piquerobi');
INSERT INTO city (id_state, name) values (1,'Piquete');
INSERT INTO city (id_state, name) values (1,'Piracaia');
INSERT INTO city (id_state, name) values (1,'Piracicaba');
INSERT INTO city (id_state, name) values (1,'Piraju');
INSERT INTO city (id_state, name) values (1,'Pirajuí');
INSERT INTO city (id_state, name) values (1,'Pirangi');
INSERT INTO city (id_state, name) values (1,'Pirapora do Bom Jesus');
INSERT INTO city (id_state, name) values (1,'Pirapozinho');
INSERT INTO city (id_state, name) values (1,'Pirassununga');
INSERT INTO city (id_state, name) values (1,'Piratininga');
INSERT INTO city (id_state, name) values (1,'Pitangueiras');
INSERT INTO city (id_state, name) values (1,'Planalto');
INSERT INTO city (id_state, name) values (1,'Platina');
INSERT INTO city (id_state, name) values (1,'Poá');
INSERT INTO city (id_state, name) values (1,'Poloni');
INSERT INTO city (id_state, name) values (1,'Pompéia');
INSERT INTO city (id_state, name) values (1,'Pongaí');
INSERT INTO city (id_state, name) values (1,'Pontal');
INSERT INTO city (id_state, name) values (1,'Pontalinda');
INSERT INTO city (id_state, name) values (1,'Pontes Gestal');
INSERT INTO city (id_state, name) values (1,'Populina');
INSERT INTO city (id_state, name) values (1,'Porangaba');
INSERT INTO city (id_state, name) values (1,'Porto Feliz');
INSERT INTO city (id_state, name) values (1,'Porto Ferreira');
INSERT INTO city (id_state, name) values (1,'Potim');
INSERT INTO city (id_state, name) values (1,'Potirendaba');
INSERT INTO city (id_state, name) values (1,'Pracinha');
INSERT INTO city (id_state, name) values (1,'Pradópolis');
INSERT INTO city (id_state, name) values (1,'Praia Grande');
INSERT INTO city (id_state, name) values (1,'Pratânia');
INSERT INTO city (id_state, name) values (1,'Presidente Alves');
INSERT INTO city (id_state, name) values (1,'Presidente Bernardes');
INSERT INTO city (id_state, name) values (1,'Presidente Epitácio');
INSERT INTO city (id_state, name) values (1,'Presidente Prudente');
INSERT INTO city (id_state, name) values (1,'Presidente Venceslau');
INSERT INTO city (id_state, name) values (1,'Promissão');
INSERT INTO city (id_state, name) values (1,'Quadra');
INSERT INTO city (id_state, name) values (1,'Quatá');
INSERT INTO city (id_state, name) values (1,'Queiroz');
INSERT INTO city (id_state, name) values (1,'Queluz');
INSERT INTO city (id_state, name) values (1,'Quintana');
INSERT INTO city (id_state, name) values (1,'Rafard');
INSERT INTO city (id_state, name) values (1,'Rancharia');
INSERT INTO city (id_state, name) values (1,'Redenção da Serra');
INSERT INTO city (id_state, name) values (1,'Regente Feijó');
INSERT INTO city (id_state, name) values (1,'Reginópolis');
INSERT INTO city (id_state, name) values (1,'Registro');
INSERT INTO city (id_state, name) values (1,'Restinga');
INSERT INTO city (id_state, name) values (1,'Ribeira');
INSERT INTO city (id_state, name) values (1,'Ribeirão Bonito');
INSERT INTO city (id_state, name) values (1,'Ribeirão Branco');
INSERT INTO city (id_state, name) values (1,'Ribeirão Corrente');
INSERT INTO city (id_state, name) values (1,'Ribeirão do Sul');
INSERT INTO city (id_state, name) values (1,'Ribeirão dos Índios');
INSERT INTO city (id_state, name) values (1,'Ribeirão Grande');
INSERT INTO city (id_state, name) values (1,'Ribeirão Pires');
INSERT INTO city (id_state, name) values (1,'Ribeirão Preto');
INSERT INTO city (id_state, name) values (1,'Riversul');
INSERT INTO city (id_state, name) values (1,'Rifaina');
INSERT INTO city (id_state, name) values (1,'Rincão');
INSERT INTO city (id_state, name) values (1,'Rinópolis');
INSERT INTO city (id_state, name) values (1,'Rio Claro');
INSERT INTO city (id_state, name) values (1,'Rio das Pedras');
INSERT INTO city (id_state, name) values (1,'Rio Grande da Serra');
INSERT INTO city (id_state, name) values (1,'Riolândia');
INSERT INTO city (id_state, name) values (1,'Rosana');
INSERT INTO city (id_state, name) values (1,'Roseira');
INSERT INTO city (id_state, name) values (1,'Rubiácea');
INSERT INTO city (id_state, name) values (1,'Rubinéia');
INSERT INTO city (id_state, name) values (1,'Sabino');
INSERT INTO city (id_state, name) values (1,'Sagres');
INSERT INTO city (id_state, name) values (1,'Sales');
INSERT INTO city (id_state, name) values (1,'Sales Oliveira');
INSERT INTO city (id_state, name) values (1,'Salesópolis');
INSERT INTO city (id_state, name) values (1,'Salmourão');
INSERT INTO city (id_state, name) values (1,'Saltinho');
INSERT INTO city (id_state, name) values (1,'Salto');
INSERT INTO city (id_state, name) values (1,'Salto de Pirapora');
INSERT INTO city (id_state, name) values (1,'Salto Grande');
INSERT INTO city (id_state, name) values (1,'Sandovalina');
INSERT INTO city (id_state, name) values (1,'Santa Adélia');
INSERT INTO city (id_state, name) values (1,'Santa Albertina');
INSERT INTO city (id_state, name) values (1,'Santa Bárbara D''Oeste');
INSERT INTO city (id_state, name) values (1,'Santa Branca');
INSERT INTO city (id_state, name) values (1,'Santa Clara D''Oeste');
INSERT INTO city (id_state, name) values (1,'Santa Cruz da Conceição');
INSERT INTO city (id_state, name) values (1,'Santa Cruz da Esperança');
INSERT INTO city (id_state, name) values (1,'Santa Cruz das Palmeiras');
INSERT INTO city (id_state, name) values (1,'Santa Cruz do Rio Pardo');
INSERT INTO city (id_state, name) values (1,'Santa Ernestina');
INSERT INTO city (id_state, name) values (1,'Santa Fé do Sul');
INSERT INTO city (id_state, name) values (1,'Santa Gertrudes');
INSERT INTO city (id_state, name) values (1,'Santa Isabel');
INSERT INTO city (id_state, name) values (1,'Santa Lúcia');
INSERT INTO city (id_state, name) values (1,'Santa Maria da Serra');
INSERT INTO city (id_state, name) values (1,'Santa Mercedes');
INSERT INTO city (id_state, name) values (1,'Santana da Ponte Pensa');
INSERT INTO city (id_state, name) values (1,'Santana de Parnaíba');
INSERT INTO city (id_state, name) values (1,'Santa Rita D''Oeste');
INSERT INTO city (id_state, name) values (1,'Santa Rita do Passa Quatro');
INSERT INTO city (id_state, name) values (1,'Santa Rosa de Viterbo');
INSERT INTO city (id_state, name) values (1,'Santa Salete');
INSERT INTO city (id_state, name) values (1,'Santo Anastácio');
INSERT INTO city (id_state, name) values (1,'Santo André');
INSERT INTO city (id_state, name) values (1,'Santo Antônio da Alegria');
INSERT INTO city (id_state, name) values (1,'Santo Antônio de Posse');
INSERT INTO city (id_state, name) values (1,'Santo Antônio do Aracanguá');
INSERT INTO city (id_state, name) values (1,'Santo Antônio do Jardim');
INSERT INTO city (id_state, name) values (1,'Santo Antônio do Pinhal');
INSERT INTO city (id_state, name) values (1,'Santo Expedito');
INSERT INTO city (id_state, name) values (1,'Santópolis do Aguapeí');
INSERT INTO city (id_state, name) values (1,'Santos');
INSERT INTO city (id_state, name) values (1,'São Bento do Sapucaí');
INSERT INTO city (id_state, name) values (1,'São Bernardo do Campo');
INSERT INTO city (id_state, name) values (1,'São Caetano do Sul');
INSERT INTO city (id_state, name) values (1,'São Carlos');
INSERT INTO city (id_state, name) values (1,'São Francisco');
INSERT INTO city (id_state, name) values (1,'São João da Boa Vista');
INSERT INTO city (id_state, name) values (1,'São João das Duas Pontes');
INSERT INTO city (id_state, name) values (1,'São João de Iracema');
INSERT INTO city (id_state, name) values (1,'São João do Pau D''Alho');
INSERT INTO city (id_state, name) values (1,'São Joaquim da Barra');
INSERT INTO city (id_state, name) values (1,'São José da Bela Vista');
INSERT INTO city (id_state, name) values (1,'São José do Barreiro');
INSERT INTO city (id_state, name) values (1,'São José do Rio Pardo');
INSERT INTO city (id_state, name) values (1,'São José do Rio Preto');
INSERT INTO city (id_state, name) values (1,'São José dos Campos');
INSERT INTO city (id_state, name) values (1,'São Lourenço da Serra');
INSERT INTO city (id_state, name) values (1,'São Luís do Paraitinga');
INSERT INTO city (id_state, name) values (1,'São Manuel');
INSERT INTO city (id_state, name) values (1,'São Miguel Arcanjo');
INSERT INTO city (id_state, name) values (1,'São Paulo');
INSERT INTO city (id_state, name) values (1,'São Pedro');
INSERT INTO city (id_state, name) values (1,'São Pedro do Turvo');
INSERT INTO city (id_state, name) values (1,'São Roque');
INSERT INTO city (id_state, name) values (1,'São Sebastião');
INSERT INTO city (id_state, name) values (1,'São Sebastião da Grama');
INSERT INTO city (id_state, name) values (1,'São Simão');
INSERT INTO city (id_state, name) values (1,'São Vicente');
INSERT INTO city (id_state, name) values (1,'Sarapuí');
INSERT INTO city (id_state, name) values (1,'Sarutaiá');
INSERT INTO city (id_state, name) values (1,'Sebastianópolis do Sul');
INSERT INTO city (id_state, name) values (1,'Serra Azul');
INSERT INTO city (id_state, name) values (1,'Serrana');
INSERT INTO city (id_state, name) values (1,'Serra Negra');
INSERT INTO city (id_state, name) values (1,'Sertãozinho');
INSERT INTO city (id_state, name) values (1,'Sete Barras');
INSERT INTO city (id_state, name) values (1,'Severínia');
INSERT INTO city (id_state, name) values (1,'Silveiras');
INSERT INTO city (id_state, name) values (1,'Socorro');
INSERT INTO city (id_state, name) values (1,'Sorocaba');
INSERT INTO city (id_state, name) values (1,'Sud Mennucci');
INSERT INTO city (id_state, name) values (1,'Sumaré');
INSERT INTO city (id_state, name) values (1,'Suzano');
INSERT INTO city (id_state, name) values (1,'Suzanápolis');
INSERT INTO city (id_state, name) values (1,'Tabapuã');
INSERT INTO city (id_state, name) values (1,'Tabatinga');
INSERT INTO city (id_state, name) values (1,'Taboão da Serra');
INSERT INTO city (id_state, name) values (1,'Taciba');
INSERT INTO city (id_state, name) values (1,'Taguaí');
INSERT INTO city (id_state, name) values (1,'Taiaçu');
INSERT INTO city (id_state, name) values (1,'Taiúva');
INSERT INTO city (id_state, name) values (1,'Tambaú');
INSERT INTO city (id_state, name) values (1,'Tanabi');
INSERT INTO city (id_state, name) values (1,'Tapiraí');
INSERT INTO city (id_state, name) values (1,'Tapiratiba');
INSERT INTO city (id_state, name) values (1,'Taquaral');
INSERT INTO city (id_state, name) values (1,'Taquaritinga');
INSERT INTO city (id_state, name) values (1,'Taquarituba');
INSERT INTO city (id_state, name) values (1,'Taquarivaí');
INSERT INTO city (id_state, name) values (1,'Tarabai');
INSERT INTO city (id_state, name) values (1,'Tarumã');
INSERT INTO city (id_state, name) values (1,'Tatuí');
INSERT INTO city (id_state, name) values (1,'Taubaté');
INSERT INTO city (id_state, name) values (1,'Tejupá');
INSERT INTO city (id_state, name) values (1,'Teodoro Sampaio');
INSERT INTO city (id_state, name) values (1,'Terra Roxa');
INSERT INTO city (id_state, name) values (1,'Tietê');
INSERT INTO city (id_state, name) values (1,'Timburi');
INSERT INTO city (id_state, name) values (1,'Torre de Pedra');
INSERT INTO city (id_state, name) values (1,'Torrinha');
INSERT INTO city (id_state, name) values (1,'Trabiju');
INSERT INTO city (id_state, name) values (1,'Tremembé');
INSERT INTO city (id_state, name) values (1,'Três Fronteiras');
INSERT INTO city (id_state, name) values (1,'Tuiuti');
INSERT INTO city (id_state, name) values (1,'Tupã');
INSERT INTO city (id_state, name) values (1,'Tupi Paulista');
INSERT INTO city (id_state, name) values (1,'Turiúba');
INSERT INTO city (id_state, name) values (1,'Turmalina');
INSERT INTO city (id_state, name) values (1,'Ubarana');
INSERT INTO city (id_state, name) values (1,'Ubatuba');
INSERT INTO city (id_state, name) values (1,'Ubirajara');
INSERT INTO city (id_state, name) values (1,'Uchoa');
INSERT INTO city (id_state, name) values (1,'União Paulista');
INSERT INTO city (id_state, name) values (1,'Urânia');
INSERT INTO city (id_state, name) values (1,'Uru');
INSERT INTO city (id_state, name) values (1,'Urupês');
INSERT INTO city (id_state, name) values (1,'Valentim Gentil');
INSERT INTO city (id_state, name) values (1,'Valinhos');
INSERT INTO city (id_state, name) values (1,'Valparaíso');
INSERT INTO city (id_state, name) values (1,'Vargem');
INSERT INTO city (id_state, name) values (1,'Vargem Grande do Sul');
INSERT INTO city (id_state, name) values (1,'Vargem Grande Paulista');
INSERT INTO city (id_state, name) values (1,'Várzea Paulista');
INSERT INTO city (id_state, name) values (1,'Vera Cruz');
INSERT INTO city (id_state, name) values (1,'Vinhedo');
INSERT INTO city (id_state, name) values (1,'Viradouro');
INSERT INTO city (id_state, name) values (1,'Vista Alegre do Alto');
INSERT INTO city (id_state, name) values (1,'Vitória Brasil');
INSERT INTO city (id_state, name) values (1,'Votorantim');
INSERT INTO city (id_state, name) values (1,'Votuporanga');
INSERT INTO city (id_state, name) values (1,'Zacarias');
INSERT INTO city (id_state, name) values (1,'Chavantes');
INSERT INTO city (id_state, name) values (1,'Estiva Gerbi');

-- Cities from Rio De Janeiro state

INSERT INTO city (id_state, name) values (2,'Angra dos Reis');
INSERT INTO city (id_state, name) values (2,'Aperibé');
INSERT INTO city (id_state, name) values (2,'Araruama');
INSERT INTO city (id_state, name) values (2,'Areal');
INSERT INTO city (id_state, name) values (2,'Armação dos Búzios');
INSERT INTO city (id_state, name) values (2,'Arraial do Cabo');
INSERT INTO city (id_state, name) values (2,'Barra do Piraí');
INSERT INTO city (id_state, name) values (2,'Barra Mansa');
INSERT INTO city (id_state, name) values (2,'Belford Roxo');
INSERT INTO city (id_state, name) values (2,'Bom Jardim');
INSERT INTO city (id_state, name) values (2,'Bom Jesus do Itabapoana');
INSERT INTO city (id_state, name) values (2,'Cabo Frio');
INSERT INTO city (id_state, name) values (2,'Cachoeiras de Macacu');
INSERT INTO city (id_state, name) values (2,'Cambuci');
INSERT INTO city (id_state, name) values (2,'Carapebus');
INSERT INTO city (id_state, name) values (2,'Comendador Levy Gasparian');
INSERT INTO city (id_state, name) values (2,'Campos dos Goytacazes');
INSERT INTO city (id_state, name) values (2,'Cantagalo');
INSERT INTO city (id_state, name) values (2,'Cardoso Moreira');
INSERT INTO city (id_state, name) values (2,'Carmo');
INSERT INTO city (id_state, name) values (2,'Casimiro de Abreu');
INSERT INTO city (id_state, name) values (2,'Conceição de Macabu');
INSERT INTO city (id_state, name) values (2,'Cordeiro');
INSERT INTO city (id_state, name) values (2,'Duas Barras');
INSERT INTO city (id_state, name) values (2,'Duque de Caxias');
INSERT INTO city (id_state, name) values (2,'Engenheiro Paulo de Frontin');
INSERT INTO city (id_state, name) values (2,'Guapimirim');
INSERT INTO city (id_state, name) values (2,'Iguaba Grande');
INSERT INTO city (id_state, name) values (2,'Itaboraí');
INSERT INTO city (id_state, name) values (2,'Itaguaí');
INSERT INTO city (id_state, name) values (2,'Italva');
INSERT INTO city (id_state, name) values (2,'Itaocara');
INSERT INTO city (id_state, name) values (2,'Itaperuna');
INSERT INTO city (id_state, name) values (2,'Itatiaia');
INSERT INTO city (id_state, name) values (2,'Japeri');
INSERT INTO city (id_state, name) values (2,'Laje do Muriaé');
INSERT INTO city (id_state, name) values (2,'Macaé');
INSERT INTO city (id_state, name) values (2,'Macuco');
INSERT INTO city (id_state, name) values (2,'Magé');
INSERT INTO city (id_state, name) values (2,'Mangaratiba');
INSERT INTO city (id_state, name) values (2,'Maricá');
INSERT INTO city (id_state, name) values (2,'Mendes');
INSERT INTO city (id_state, name) values (2,'Mesquita');
INSERT INTO city (id_state, name) values (2,'Miguel Pereira');
INSERT INTO city (id_state, name) values (2,'Miracema');
INSERT INTO city (id_state, name) values (2,'Natividade');
INSERT INTO city (id_state, name) values (2,'Nilópolis');
INSERT INTO city (id_state, name) values (2,'Niterói');
INSERT INTO city (id_state, name) values (2,'Nova Friburgo');
INSERT INTO city (id_state, name) values (2,'Nova Iguaçu');
INSERT INTO city (id_state, name) values (2,'Paracambi');
INSERT INTO city (id_state, name) values (2,'Paraíba do Sul');
INSERT INTO city (id_state, name) values (2,'Paraty');
INSERT INTO city (id_state, name) values (2,'Paty do Alferes');
INSERT INTO city (id_state, name) values (2,'Petrópolis');
INSERT INTO city (id_state, name) values (2,'Pinheiral');
INSERT INTO city (id_state, name) values (2,'Piraí');
INSERT INTO city (id_state, name) values (2,'Porciúncula');
INSERT INTO city (id_state, name) values (2,'Porto Real');
INSERT INTO city (id_state, name) values (2,'Quatis');
INSERT INTO city (id_state, name) values (2,'Queimados');
INSERT INTO city (id_state, name) values (2,'Quissamã');
INSERT INTO city (id_state, name) values (2,'Resende');
INSERT INTO city (id_state, name) values (2,'Rio Bonito');
INSERT INTO city (id_state, name) values (2,'Rio Claro');
INSERT INTO city (id_state, name) values (2,'Rio das Flores');
INSERT INTO city (id_state, name) values (2,'Rio das Ostras');
INSERT INTO city (id_state, name) values (2,'Rio de Janeiro');
INSERT INTO city (id_state, name) values (2,'Santa Maria Madalena');
INSERT INTO city (id_state, name) values (2,'Santo Antônio de Pádua');
INSERT INTO city (id_state, name) values (2,'São Francisco de Itabapoana');
INSERT INTO city (id_state, name) values (2,'São Fidélis');
INSERT INTO city (id_state, name) values (2,'São Gonçalo');
INSERT INTO city (id_state, name) values (2,'São João da Barra');
INSERT INTO city (id_state, name) values (2,'São João de Meriti');
INSERT INTO city (id_state, name) values (2,'São José de Ubá');
INSERT INTO city (id_state, name) values (2,'São José do Vale do Rio Preto');
INSERT INTO city (id_state, name) values (2,'São Pedro da Aldeia');
INSERT INTO city (id_state, name) values (2,'São Sebastião do Alto');
INSERT INTO city (id_state, name) values (2,'Sapucaia');
INSERT INTO city (id_state, name) values (2,'Saquarema');
INSERT INTO city (id_state, name) values (2,'Seropédica');
INSERT INTO city (id_state, name) values (2,'Silva Jardim');
INSERT INTO city (id_state, name) values (2,'Sumidouro');
INSERT INTO city (id_state, name) values (2,'Tanguá');
INSERT INTO city (id_state, name) values (2,'Teresópolis');
INSERT INTO city (id_state, name) values (2,'Trajano de Moraes');
INSERT INTO city (id_state, name) values (2,'Três Rios');
INSERT INTO city (id_state, name) values (2,'Valença');
INSERT INTO city (id_state, name) values (2,'Varre-Sai');
INSERT INTO city (id_state, name) values (2,'Vassouras');
INSERT INTO city (id_state, name) values (2,'Volta Redonda');