quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://postgres-1.cpseq604e9xb.us-east-1.rds.amazonaws.com:5432/product
    username: product_user
    password: postgres
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

"%vagrant":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://postgres-1.cpseq604e9xb.us-east-1.rds.amazonaws.com:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log: 
        sql: true
    container-image:
      build: true
      name: ecommerce-quarkus
      group: thiagovdcr
      username: thiagovdcr
      registry: ghcr.io
      push: true
    kubernetes: 
      generate-image-pull-secret: true
      ports:
        '"http"': 
          container-port: 8080
          host-port: 90
      namespace: default

"%native":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://postgres-1.cpseq604e9xb.us-east-1.rds.amazonaws.com:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log:
        sql: true
