quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://postgres-1.cpseq604e9xb.us-east-1.rds.amazonaws.com:5432/product
    username: product_user
    password: postgres
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

"%vagrant":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://postgres-1.cpseq604e9xb.us-east-1.rds.amazonaws.com:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log: true

"%native":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://postgres-1.cpseq604e9xb.us-east-1.rds.amazonaws.com:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log:
        sql: true
