quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/product
    username: product_user
    password: postgres
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

"%native":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://172.17.0.2:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log:
        sql: true
    native:
        enabled: true
        builder-image: graalvm
        native-image-xmx: 4g
        container-build: true
    package:
      jar:
        enabled: false
    docker:
      buildx:
        platform: linux/arm64
        output: type=docker
    container-image:
      builder: docker
      build: true