quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/product
    username: product_user
    password: postgres
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

"%vagrant":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://10.0.0.2:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log:

"%native":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://172.17.0.2:5432/product
      username: product_user
      password: postgres
    hibernate-orm:
      database:
        generation: none
      log:
        sql: true
